export const CONTRACT_LIST_WATCH_OPTIONS = {
  status: '상태',
  userName: '담당자',
  cityName: '지역',
  contractAt: '계약일',
  shippingDate: '출고일',
  name: '고객명',
  phone: '연락처',
  carName: '차종',
  carOption: '옵션',
  innerColor: '외장색상',
  outerColor: '내장색상',
  carPrice: '차량가',
  financialCompany: '금융사',
  product: '상품',
  surtax: '부가세',
  feeRate: '수수료율',
  fee: '수수료금액',
  promotion: '프로모션',
  interChangeFee: '정산수수료',
  monthlyPayment: '월납입료',
  shippingMethod: '출고방식',
  isOrdering: '발주여부',
  branch: '지점',
  branchFee: '지점수수료',
  collateralType: '담보종류',
  collateralRate: '담보율',
  contractPeriod: '약정기간',
  agreedMileage: '약정거리',
  insuranceAge: '보험연령',
  object: '대물',
  service1: '서비스1',
  serviceBody1: '내용1',
  service2: '서비스2',
  serviceBody2: '내용2',
  service3: '서비스3',
  serviceBody3: '내용3',
  incomeEarner: '소득자',
  cashAssistance: '현금지원',
  supportDetails: '지원내용',
  businessExpenses: '발비',
  businessExpensesDetail: '발비내용',
  totalExpenditure: '총지출',
  totalFee: '수수료합계',
  netIncome: '순수익',
};

export const CONTRACT_LIST_WATCH_REQUIRED_OPTIONS = [
  'status',
  'contractAt',
  'shippingDate',
  'name',
  'phone',
  'carName',
  'carPrice',
  'financialCompany',
  'product',
  'feeRate',
  'fee',
  'promotion',
  'interChangeFee',
  'monthlyPayment',
  'shippingMethod',
  'totalFee',
];
