export const CONTRACT_LIST_WATCH_OPTIONS = {
  customerStatus: '상태',
  userName: '담당자',
  cityName: '지역',
  contractAt: '계약일',
  shippingDate: '출고일',
  customerName: '고객명',
  customerPhone: '연락처',
  carName: '차종',
  carOption: '차 옵션',
  innerColor: '외장색상',
  outerColor: '내장색상',
  carPrice: '차량가',
  financialCompany: '금융사',
  feeRate: '수수료율',
  fee: '수수료금액',
  promotion: '프로모션',
  monthlyPayment: '월납입료',
  shippingMethod: '출고방식',
  isOrdering: '출고여부',
  branch: '지점명',
  branchFee: '지점수수료',
  advancePayment: '선납금',
  security: '보증금',
  contractPeriod: '약정기간',
  agreedMileage: '약정거리',
  insuranceAge: '보험연령',
  object: '대물',
  service1: '품의 금액 1',
  serviceBody1: '품의 내용 1',
  service2: '품의 금액 2',
  serviceBody2: '품의 내용 2',
  service3: '품의 금액 3',
  serviceBody3: '품의 내용 3',
  incomeEarner: '소득자',
  cashAssistance: '현금지원',
  supportDetails: '지원내용',
  businessExpenses: '경비',
  businessExpensesDetail: '경비내용',
  totalExpenditure: '지출합계',
  totalFee: '매출합계',
  netIncome: '순익합계',
  company_name_nominee: '회사명/명의자',
  divisionName: '구분',
};

export const CONTRACT_LIST_WATCH_REQUIRED_OPTIONS = [
  'customerStatus',
  'cityName',
  'contractAt',
  'customerName',
  'customerPhone',
  'carName',
  'carOption',
  'innerColor',
  'outerColor',
  'carPrice',
  'financialCompany',
  'feeRate',
  'fee',
  'promotion',
  'monthlyPayment',
  'shippingMethod',
  'branch',
  'branchFee',
  'advancePayment',
  'security',
  'contractPeriod',
  'agreedMileage',
  'insuranceAge',
  'object',
];

// 저쪽에서 요청한 필수값인데, 이렇게 요청했다가 또 관리자 아닌 유저는 필수값만 보이게 해달라해서 일단 주석
// export const CONTRACT_LIST_WATCH_REQUIRED_OPTIONS = [
//     'status',
//     'contractAt',
//     'shippingDate',
//     'name',
//     'phone',
//     'carName',
//     'carPrice',
//     'financialCompany',
//     'feeRate',
//     'fee',
//     'totalExpenditure',
//     'totalFee',
//     'netIncome',
//   ];
