// import { TCustomerList } from '@/types/customer';

// export const dummyCustomerList: TCustomerList[] = [
//   {
//     address: '주소',
//     birth: '생년월일',
//     created_at: '고객 생성일시',
//     customerGroup: {
//       id: 1,
//       name: '고객그룹',
//       createdAt: '생성',
//       updatedAt: '수정',
//       deletedAt: '삭제',
//     },
//     email: '이메일',
//     id: 1,
//     job: '직업',
//     name: '테스트1',
//     phone: '010-4405-1001',
//     status: '정상',
//     updated_at: '고객 마지막 수정일시',
//   },
//   {
//     address: '주소',
//     birth: '생년월일',
//     created_at: '고객 생성일시',
//     customerGroup: {
//       id: 1,
//       name: '고객그룹',
//       createdAt: '생성',
//       updatedAt: '수정',
//       deletedAt: '삭제',
//     },
//     email: '이메일',
//     id: 2,
//     job: '직업',
//     name: '테스트1',
//     phone: '010-4405-1001',
//     status: '정상',
//     updated_at: '고객 마지막 수정일시',
//   },
//   {
//     address: '주소',
//     birth: '생년월일',
//     created_at: '고객 생성일시',
//     customerGroup: {
//       id: 1,
//       name: '고객그룹',
//       createdAt: '생성',
//       updatedAt: '수정',
//       deletedAt: '삭제',
//     },
//     email: '이메일',
//     id: 3,
//     job: '직업',
//     name: '테스트1',
//     phone: '010-4405-1001',
//     status: '정상',
//     updated_at: '고객 마지막 수정일시',
//   },
// ];
